# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to FireBase Beta Distribution"
  lane :beta do |options|
    firebase_app_distribution(
          app: "1:1082201721355:android:6d2190a84bce23951ed50e",
          groups: options[:group],
          release_notes: options[:desc],
          apk_path: options[:project_root]
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store
  end


end
